INSTALL_TARGET_PROCESSES = SpringBoard

export ARCHS = armv7 arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Pasteboard

Pasteboard_FILES = Tweak.x
Pasteboard_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
