INSTALL_TARGET_PROCESSES = SpringBoard

export ARCHS = arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = NoNCTitle

NoNCTitle_FILES = Tweak.x
NoNCTitle_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
