INSTALL_TARGET_PROCESSES = SpringBoard

export ARCHS = armv7 arm64 arm64e

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = UnlockVol13

UnlockVol13_FILES = Tweak.x
UnlockVol13_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
